import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

type Lang = "en" | "it";

const translations = {
  en: {
    appSlogan: "Always Close, Always Caring.",
    appName: "CuraVicino",
    welcome: "Welcome to CuraVicino",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    phone: "Phone Number",
    fullName: "Full Name",
    age: "Age",
    address: "Address",
    continueWith: "Continue with",
    google: "Google",
    facebook: "Facebook",
    orEmail: "or continue with email",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signUp: "Sign Up",
    signIn: "Sign In",
    iAmA: "I am a...",
    customer: "Customer",
    serviceProvider: "Service Provider",
    forWhom: "Is this service for yourself or a family member?",
    myself: "Myself",
    familyMember: "A Family Member",
    uploadId: "Upload Government ID",
    uploadMedical: "Upload Medical Certificate",
    uploadCriminal: "Upload Clean Criminal Record",
    uploadPhoto: "Upload Personal Photo",
    linkBanking: "Link Banking Account",
    withdrawal: "Withdrawal Preference",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    categories: "Our Services",
    elderlyCare: "Elderly & Medical Care",
    elderlyDesc: "Professional care for your loved ones",
    delivery: "Delivery & Shopping",
    deliveryDesc: "Pharmacy, groceries, and more",
    homeServices: "Home Services",
    homeServicesDesc: "Cleaning, plumbing, gardening & more",
    bookNow: "Book Now",
    findProvider: "Find a Provider",
    myBookings: "My Bookings",
    notifications: "Notifications",
    profile: "Profile",
    home: "Home",
    settings: "Settings",
    support: "Support",
    terms: "Terms & Conditions",
    complaints: "File a Complaint",
    ratingsReviews: "Ratings & Reviews",
    tracking: "Live Tracking",
    providerDashboard: "Provider Dashboard",
    earnings: "Earnings",
    qrCode: "My QR Code",
    acceptRequest: "Accept",
    rejectRequest: "Reject",
    pending: "Pending",
    active: "Active",
    completed: "Completed",
    cancelled: "Cancelled",
    logout: "Logout",
    saveChanges: "Save Changes",
    back: "Back",
    submit: "Submit",
    cancel: "Cancel",
    confirm: "Confirm",
    next: "Next",
    skip: "Skip",
    search: "Search services...",
    noBookings: "No bookings yet",
    noNotifications: "No notifications",
    callSupport: "Call Support",
    supportNumber: "+39 800 123 456",
    serviceFeeMedical: "Service fee: 23%",
    serviceFeeDelivery: "Service fee: 25%",
    serviceFeeHome: "Service fee: 22%",
    paymentMethods: "Payment Methods",
    paypal: "PayPal",
    stripe: "Credit/Debit Card",
    language: "Language",
    english: "English",
    italian: "Italian",
    providerNote: "Provider will call before delivery",
    complaintTitle: "Complaint Title",
    complaintDesc: "Describe your issue",
    doctorCompanion: "Doctor Companion",
    hourlyCare: "Hourly Care",
    fullTimeCare: "Full-Time Live-In Care",
    alzheimerCare: "Alzheimer Care",
    dementiaCare: "Dementia Care",
    disabilitySupport: "Disability Support",
    autismSupport: "Autism Support",
    downSyndromeSupport: "Down Syndrome Support",
    brainInjurySupport: "Brain Injury Support",
    fullAssistance: "Full Assistance",
    pharmacyShopping: "Pharmacy Shopping",
    localStoreShopping: "Local Store Shopping",
    mallShopping: "Mall Shopping",
    restaurantDelivery: "Restaurant Delivery",
    houseCleaning: "House Cleaning",
    plumbing: "Plumbing",
    carpentry: "Carpentry",
    electricalRepair: "Electrical Repair",
    gardening: "Gardening",
    homeMaintenance: "Small Home Maintenance",
    registerSuccess: "Registration Successful!",
    reviewSubmitted: "Review Submitted",
    bookingConfirmed: "Booking Confirmed",
    required: "This field is required",
    invalidEmail: "Invalid email address",
    providerVerification: "Your documents are being reviewed. You will be notified within 24 hours.",
    welcomeBack: "Welcome back",
    chooseAccount: "Choose Account Type",
    uploading: "Uploading...",
    uploaded: "Uploaded",
    tapToUpload: "Tap to upload",
    selectService: "Select a Service",
    availableProviders: "Available Providers",
    rating: "Rating",
    reviews: "Reviews",
    experience: "Experience",
    verified: "Verified",
    perHour: "per hour",
    total: "Total",
    bookingDetails: "Booking Details",
    date: "Date",
    time: "Time",
    duration: "Duration",
    notes: "Additional Notes",
    privacyPolicy: "Privacy Policy",
    deleteAccount: "Delete Account",
  },
  it: {
    appSlogan: "Sempre Vicino, Sempre Premuroso.",
    appName: "CuraVicino",
    welcome: "Benvenuto su CuraVicino",
    login: "Accedi",
    register: "Registrati",
    email: "Email",
    password: "Password",
    phone: "Numero di Telefono",
    fullName: "Nome Completo",
    age: "Età",
    address: "Indirizzo",
    continueWith: "Continua con",
    google: "Google",
    facebook: "Facebook",
    orEmail: "o continua con email",
    forgotPassword: "Password Dimenticata?",
    noAccount: "Non hai un account?",
    haveAccount: "Hai già un account?",
    signUp: "Registrati",
    signIn: "Accedi",
    iAmA: "Sono un...",
    customer: "Cliente",
    serviceProvider: "Fornitore di Servizi",
    forWhom: "Il servizio è per te o per un familiare?",
    myself: "Per me",
    familyMember: "Per un Familiare",
    uploadId: "Carica Documento d'Identità",
    uploadMedical: "Carica Certificato Medico",
    uploadCriminal: "Carica Casellario Giudiziario",
    uploadPhoto: "Carica Foto Personale",
    linkBanking: "Collega Conto Bancario",
    withdrawal: "Preferenza Prelievo",
    daily: "Giornaliero",
    weekly: "Settimanale",
    monthly: "Mensile",
    categories: "I Nostri Servizi",
    elderlyCare: "Assistenza Anziani e Medica",
    elderlyDesc: "Cura professionale per i tuoi cari",
    delivery: "Consegna e Spesa",
    deliveryDesc: "Farmacia, alimentari e altro",
    homeServices: "Servizi Domestici",
    homeServicesDesc: "Pulizia, idraulica, giardinaggio e altro",
    bookNow: "Prenota Ora",
    findProvider: "Trova un Fornitore",
    myBookings: "Le Mie Prenotazioni",
    notifications: "Notifiche",
    profile: "Profilo",
    home: "Home",
    settings: "Impostazioni",
    support: "Supporto",
    terms: "Termini e Condizioni",
    complaints: "Presenta un Reclamo",
    ratingsReviews: "Valutazioni e Recensioni",
    tracking: "Tracciamento in Tempo Reale",
    providerDashboard: "Dashboard Fornitore",
    earnings: "Guadagni",
    qrCode: "Il Mio QR Code",
    acceptRequest: "Accetta",
    rejectRequest: "Rifiuta",
    pending: "In Attesa",
    active: "Attivo",
    completed: "Completato",
    cancelled: "Annullato",
    logout: "Esci",
    saveChanges: "Salva Modifiche",
    back: "Indietro",
    submit: "Invia",
    cancel: "Annulla",
    confirm: "Conferma",
    next: "Avanti",
    skip: "Salta",
    search: "Cerca servizi...",
    noBookings: "Nessuna prenotazione",
    noNotifications: "Nessuna notifica",
    callSupport: "Chiama Supporto",
    supportNumber: "+39 800 123 456",
    serviceFeeMedical: "Commissione servizio: 23%",
    serviceFeeDelivery: "Commissione servizio: 25%",
    serviceFeeHome: "Commissione servizio: 22%",
    paymentMethods: "Metodi di Pagamento",
    paypal: "PayPal",
    stripe: "Carta di Credito/Debito",
    language: "Lingua",
    english: "Inglese",
    italian: "Italiano",
    providerNote: "Il fornitore chiamerà prima della consegna",
    complaintTitle: "Titolo Reclamo",
    complaintDesc: "Descrivi il tuo problema",
    doctorCompanion: "Accompagnamento dal Medico",
    hourlyCare: "Assistenza Oraria",
    fullTimeCare: "Assistenza Residenziale H24",
    alzheimerCare: "Assistenza Alzheimer",
    dementiaCare: "Assistenza Demenza",
    disabilitySupport: "Supporto Disabilità",
    autismSupport: "Supporto Autismo",
    downSyndromeSupport: "Supporto Sindrome di Down",
    brainInjurySupport: "Supporto Lesioni Cerebrali",
    fullAssistance: "Assistenza Completa",
    pharmacyShopping: "Spesa in Farmacia",
    localStoreShopping: "Spesa nel Negozio Locale",
    mallShopping: "Spesa al Centro Commerciale",
    restaurantDelivery: "Consegna Ristorante",
    houseCleaning: "Pulizia della Casa",
    plumbing: "Idraulica",
    carpentry: "Falegnameria",
    electricalRepair: "Riparazione Elettrica",
    gardening: "Giardinaggio",
    homeMaintenance: "Piccola Manutenzione",
    registerSuccess: "Registrazione Completata!",
    reviewSubmitted: "Recensione Inviata",
    bookingConfirmed: "Prenotazione Confermata",
    required: "Questo campo è obbligatorio",
    invalidEmail: "Indirizzo email non valido",
    providerVerification: "I tuoi documenti sono in revisione. Sarai notificato entro 24 ore.",
    welcomeBack: "Bentornato",
    chooseAccount: "Scegli il Tipo di Account",
    uploading: "Caricamento...",
    uploaded: "Caricato",
    tapToUpload: "Tocca per caricare",
    selectService: "Seleziona un Servizio",
    availableProviders: "Fornitori Disponibili",
    rating: "Valutazione",
    reviews: "Recensioni",
    experience: "Esperienza",
    verified: "Verificato",
    perHour: "all'ora",
    total: "Totale",
    bookingDetails: "Dettagli Prenotazione",
    date: "Data",
    time: "Orario",
    duration: "Durata",
    notes: "Note Aggiuntive",
    privacyPolicy: "Informativa sulla Privacy",
    deleteAccount: "Elimina Account",
  },
};

export type TKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    AsyncStorage.getItem("lang").then((v) => {
      if (v === "en" || v === "it") setLangState(v);
    });
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem("lang", l);
  };

  const t = (key: TKey): string => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
