import { StyleSheet } from "react-native";
import { shadow } from "@/utils/shadow";
export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  backBtn: { padding: 8 },
  headerTitle: { fontSize: 18, fontFamily: "Inter_700Bold", color: "#ffffff" },
  scroll: { paddingHorizontal: 20, paddingTop: 20 },

  stepBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 16,
  },
  stepBadgeText: { fontSize: 13, fontFamily: "Inter_700Bold" },

  fieldWrap: { marginBottom: 14 },
  label: { fontSize: 14, fontFamily: "Inter_600SemiBold", marginBottom: 6 },
  subLabel: { fontSize: 14, fontFamily: "Inter_600SemiBold", marginBottom: 10, marginTop: 4 },
  helperText: { fontSize: 12, fontFamily: "Inter_400Regular", marginBottom: 10, marginTop: -4 },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 52,
  },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, fontSize: 15, fontFamily: "Inter_400Regular" },

  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 22,
    borderWidth: 1.5,
  },
  chipText: { fontSize: 13, fontFamily: "Inter_500Medium" },

  categoryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
  },
  catIconBox: {
    width: 44,
    height: 44,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  catLabel: { flex: 1, fontSize: 15, fontFamily: "Inter_600SemiBold" },

  availRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1.5,
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
  },
  availRowLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  availDot: { width: 10, height: 10, borderRadius: 5 },
  availLabel: { fontSize: 15, fontFamily: "Inter_600SemiBold" },

  daysRow: { flexDirection: "row", gap: 6, marginBottom: 16, flexWrap: "wrap" },
  dayBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  dayTxt: { fontSize: 11, fontFamily: "Inter_700Bold" },

  hoursRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
  hourBlock: { flex: 1 },
  hourLabel: { fontSize: 12, fontFamily: "Inter_500Medium", marginBottom: 6 },
  hourInput: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 48,
  },
  hourText: { flex: 1, fontSize: 15, fontFamily: "Inter_500Medium" },
  arrowIcon: { marginTop: 20 },

  uploadRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    gap: 12,
  },
  uploadIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  uploadLabel: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  uploadStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  uploadStatusText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },

  bankingBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1.5,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
  bankingBtnText: { flex: 1, fontSize: 15, fontFamily: "Inter_600SemiBold" },

  withdrawalRow: { flexDirection: "row", gap: 10, marginBottom: 28 },
  withdrawalBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  withdrawalTxt: { fontSize: 13, fontFamily: "Inter_600SemiBold" },

  submitBtn: {
    height: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    ...shadow("#CE2B37", 0.3, 8, 4, 5),
  },
  submitBtnText: { fontSize: 16, fontFamily: "Inter_700Bold", color: "#ffffff" },
  disabled: { opacity: 0.6 },
  sectionTitle: { fontSize: 16, fontFamily: "Inter_700Bold", marginBottom: 12, marginTop: 8 },
});